# Generated by Django 6.0 on 2025-12-13 14:43

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('title', models.CharField(max_length=255, verbose_name='岗位名称')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='部门')),
                ('description', models.TextField(blank=True, verbose_name='岗位描述')),
                ('requirements', models.JSONField(default=dict, verbose_name='岗位要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '岗位',
                'verbose_name_plural': '岗位',
                'db_table': 'positions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['title'], name='positions_title_94e831_idx'), models.Index(fields=['is_active'], name='positions_is_acti_882ee8_idx')],
            },
        ),
    ]
