# Generated by Django 6.0 on 2025-12-05 00:25

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PositionCriteria',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('position', models.CharField(max_length=255, verbose_name='职位名称')),
                ('department', models.CharField(blank=True, max_length=255, verbose_name='部门')),
                ('required_skills', models.JSONField(default=list, verbose_name='必备技能')),
                ('optional_skills', models.JSONField(default=list, verbose_name='加分技能')),
                ('min_experience', models.IntegerField(default=0, verbose_name='最低工作年限')),
                ('education', models.JSONField(default=list, verbose_name='学历要求')),
                ('certifications', models.JSONField(default=list, verbose_name='证书要求')),
                ('salary_min', models.IntegerField(default=0, verbose_name='最低薪资')),
                ('salary_max', models.IntegerField(default=0, verbose_name='最高薪资')),
                ('project_requirements', models.JSONField(default=dict, verbose_name='项目经验要求')),
                ('is_active', models.BooleanField(default=True, verbose_name='是否启用')),
            ],
            options={
                'verbose_name': '岗位招聘标准',
                'verbose_name_plural': '岗位招聘标准',
                'db_table': 'position_criteria',
                'ordering': ['-created_at'],
            },
        ),
    ]
