# Generated by Django 6.0 on 2025-12-05 08:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('position_settings', '0001_initial'),
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumePositionAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='分配时间')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '简历岗位分配',
                'verbose_name_plural': '简历岗位分配',
                'db_table': 'resume_position_assignments',
                'ordering': ['-assigned_at'],
            },
        ),
        migrations.AddField(
            model_name='positioncriteria',
            name='description',
            field=models.TextField(blank=True, verbose_name='岗位描述'),
        ),
        migrations.AddField(
            model_name='positioncriteria',
            name='resume_count',
            field=models.IntegerField(default=0, verbose_name='简历数量'),
        ),
        migrations.AddField(
            model_name='positioncriteria',
            name='status',
            field=models.CharField(choices=[('pending', '待分析'), ('interview_analysis', '面试分析中'), ('interview_analysis_completed', '面试分析已完成'), ('comprehensive_screening', '综合筛选中'), ('completed', '已完成')], default='pending', max_length=30, verbose_name='筛选状态'),
        ),
        migrations.AddIndex(
            model_name='positioncriteria',
            index=models.Index(fields=['position'], name='position_cr_positio_7453e5_idx'),
        ),
        migrations.AddIndex(
            model_name='positioncriteria',
            index=models.Index(fields=['status'], name='position_cr_status_478e0b_idx'),
        ),
        migrations.AddIndex(
            model_name='positioncriteria',
            index=models.Index(fields=['is_active'], name='position_cr_is_acti_b3b1a3_idx'),
        ),
        migrations.AddField(
            model_name='resumepositionassignment',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='resume_assignments', to='position_settings.positioncriteria', verbose_name='岗位'),
        ),
        migrations.AddField(
            model_name='resumepositionassignment',
            name='resume_data',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='position_assignments', to='resume_screening.resumedata', verbose_name='简历数据'),
        ),
        migrations.AlterUniqueTogether(
            name='resumepositionassignment',
            unique_together={('position', 'resume_data')},
        ),
    ]
