# Generated by Django 6.0 on 2025-12-05 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('position_settings', '0002_resumepositionassignment_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='positioncriteria',
            name='position_cr_status_478e0b_idx',
        ),
        migrations.RemoveField(
            model_name='positioncriteria',
            name='status',
        ),
    ]
