# Generated by Django 6.0 on 2025-12-13 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprehensiveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('final_score', models.FloatField(verbose_name='综合得分')),
                ('recommendation', models.JSONField(verbose_name='推荐结果')),
                ('dimension_scores', models.JSONField(default=dict, verbose_name='维度评分')),
                ('report', models.TextField(verbose_name='综合报告')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_analyses', to='resume.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '综合分析',
                'verbose_name_plural': '综合分析',
                'db_table': 'comprehensive_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
