# Generated by Django 6.0 on 2025-12-07 16:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('final_recommend', '0001_initial'),
        ('resume_screening', '0002_resumelibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateComprehensiveAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('final_score', models.FloatField(verbose_name='综合得分')),
                ('recommendation_level', models.CharField(max_length=50, verbose_name='推荐等级')),
                ('recommendation_label', models.CharField(max_length=50, verbose_name='推荐标签')),
                ('recommendation_action', models.TextField(verbose_name='建议行动')),
                ('dimension_scores', models.JSONField(default=dict, verbose_name='维度评分详情')),
                ('comprehensive_report', models.TextField(verbose_name='综合分析报告')),
                ('input_data_snapshot', models.JSONField(default=dict, verbose_name='输入数据快照')),
                ('resume_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprehensive_analyses', to='resume_screening.resumedata', verbose_name='关联简历')),
            ],
            options={
                'verbose_name': '候选人综合分析',
                'verbose_name_plural': '候选人综合分析',
                'db_table': 'candidate_comprehensive_analyses',
                'ordering': ['-created_at'],
            },
        ),
    ]
