# Generated by Django 6.0 on 2025-12-05 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('video_analysis', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeScreeningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度百分比')),
                ('current_step', models.IntegerField(default=0, verbose_name='当前步骤')),
                ('total_steps', models.IntegerField(default=1, verbose_name='总步骤数')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('current_speaker', models.CharField(blank=True, max_length=100, null=True, verbose_name='当前发言者')),
                ('position_data', models.JSONField(blank=True, null=True, verbose_name='岗位信息')),
            ],
            options={
                'verbose_name': '简历筛选任务',
                'verbose_name_plural': '简历筛选任务',
                'db_table': 'resume_screening_tasks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('position_title', models.CharField(max_length=255, verbose_name='岗位名称')),
                ('position_details', models.JSONField(verbose_name='岗位详细信息')),
                ('position_hash', models.CharField(max_length=64, unique=True, verbose_name='岗位信息哈希值')),
                ('group_name', models.CharField(max_length=255, verbose_name='简历组名称')),
                ('description', models.TextField(blank=True, null=True, verbose_name='组描述')),
                ('resume_count', models.IntegerField(default=0, verbose_name='简历数量')),
                ('status', models.CharField(choices=[('pending', '待分析'), ('interview_analysis', '面试分析中'), ('interview_analysis_completed', '面试分析已完成'), ('comprehensive_screening', '综合筛选中'), ('completed', '已完成')], default='pending', max_length=30, verbose_name='状态')),
            ],
            options={
                'verbose_name': '简历组',
                'verbose_name_plural': '简历组',
                'db_table': 'resume_groups',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['position_title'], name='resume_grou_positio_5219f5_idx'), models.Index(fields=['position_hash'], name='resume_grou_positio_55d53f_idx'), models.Index(fields=['status'], name='resume_grou_status_120ff3_idx'), models.Index(fields=['created_at'], name='resume_grou_created_950ece_idx')],
            },
        ),
        migrations.CreateModel(
            name='ScreeningReport',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('md_file', models.FileField(upload_to='screening_reports/%Y/%m/%d/', verbose_name='MD报告文件')),
                ('original_filename', models.CharField(max_length=255, verbose_name='原始文件名')),
                ('resume_content', models.TextField(blank=True, null=True, verbose_name='简历内容')),
                ('json_report_content', models.TextField(blank=True, null=True, verbose_name='JSON报告内容')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='resume_screening.resumescreeningtask', verbose_name='关联任务')),
            ],
            options={
                'verbose_name': '筛选报告',
                'verbose_name_plural': '筛选报告',
                'db_table': 'screening_reports',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ResumeData',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('position_title', models.CharField(max_length=255, verbose_name='岗位名称')),
                ('position_details', models.JSONField(verbose_name='岗位详细信息')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='候选人姓名')),
                ('resume_content', models.TextField(verbose_name='简历内容')),
                ('screening_score', models.JSONField(blank=True, null=True, verbose_name='筛选评分')),
                ('screening_summary', models.TextField(blank=True, null=True, verbose_name='筛选总结')),
                ('resume_file_hash', models.CharField(max_length=64, unique=True, verbose_name='简历文件哈希值')),
                ('report_md_file', models.FileField(blank=True, null=True, upload_to='screening_reports/%Y/%m/%d/', verbose_name='报告MD文件')),
                ('report_json_file', models.FileField(blank=True, null=True, upload_to='screening_reports/%Y/%m/%d/', verbose_name='报告JSON文件')),
                ('json_report_content', models.TextField(blank=True, null=True, verbose_name='JSON报告内容')),
                ('video_analysis', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_resume_data', to='video_analysis.videoanalysis', verbose_name='关联视频分析')),
                ('group', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='resume_screening.resumegroup', verbose_name='关联简历组')),
                ('task', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_data', to='resume_screening.resumescreeningtask', verbose_name='关联任务')),
                ('report', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resume_data', to='resume_screening.screeningreport', verbose_name='关联报告')),
            ],
            options={
                'verbose_name': '简历数据',
                'verbose_name_plural': '简历数据',
                'db_table': 'resume_data',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['candidate_name'], name='resume_data_candida_545fc8_idx'), models.Index(fields=['position_title'], name='resume_data_positio_111d8a_idx'), models.Index(fields=['resume_file_hash'], name='resume_data_resume__9b8c34_idx'), models.Index(fields=['created_at'], name='resume_data_created_acbfa8_idx')],
            },
        ),
    ]
