# Generated by Django 6.0 on 2025-12-13 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScreeningTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('status', models.CharField(choices=[('pending', '等待中'), ('running', '进行中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('progress', models.IntegerField(default=0, verbose_name='进度%')),
                ('total_count', models.IntegerField(default=0, verbose_name='总数量')),
                ('processed_count', models.IntegerField(default=0, verbose_name='已处理数量')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='screening_tasks', to='position_settings.position', verbose_name='岗位')),
            ],
            options={
                'verbose_name': '筛选任务',
                'verbose_name_plural': '筛选任务',
                'db_table': 'screening_tasks',
                'ordering': ['-created_at'],
            },
        ),
    ]
