# Generated by Django 6.0 on 2025-12-05 14:32

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResumeLibrary',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='上传时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='文件哈希值')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小(字节)')),
                ('file_type', models.CharField(default='', max_length=50, verbose_name='文件类型')),
                ('content', models.TextField(verbose_name='简历内容(文本)')),
                ('candidate_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='候选人姓名')),
                ('is_screened', models.BooleanField(default=False, verbose_name='是否已筛选')),
                ('is_assigned', models.BooleanField(default=False, verbose_name='是否已分配岗位')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '简历库',
                'verbose_name_plural': '简历库',
                'db_table': 'resume_library',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['filename'], name='resume_libr_filenam_17bbbe_idx'), models.Index(fields=['file_hash'], name='resume_libr_file_ha_c8972c_idx'), models.Index(fields=['candidate_name'], name='resume_libr_candida_ea24ed_idx'), models.Index(fields=['is_screened'], name='resume_libr_is_scre_baf3e3_idx'), models.Index(fields=['created_at'], name='resume_libr_created_137457_idx')],
            },
        ),
    ]
