# Generated by Django 6.0 on 2025-12-14 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='screeningtask',
            name='resumes',
            field=models.ManyToManyField(blank=True, related_name='screening_tasks', to='resume.resume', verbose_name='筛选的简历'),
        ),
    ]
