# Generated by Django 6.0 on 2025-12-13 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('video_file', models.FileField(upload_to='videos/%Y/%m/%d/', verbose_name='视频文件')),
                ('video_name', models.CharField(max_length=255, verbose_name='视频名称')),
                ('status', models.CharField(choices=[('pending', '等待分析'), ('processing', '分析中'), ('completed', '已完成'), ('failed', '失败')], default='pending', max_length=20, verbose_name='状态')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='错误信息')),
                ('analysis_result', models.JSONField(blank=True, null=True, verbose_name='分析结果')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_analyses', to='resume.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '视频分析',
                'verbose_name_plural': '视频分析',
                'db_table': 'video_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='video_analy_status_72327d_idx'), models.Index(fields=['created_at'], name='video_analy_created_42fdc8_idx')],
            },
        ),
    ]
