# Generated by Django 6.0 on 2025-12-13 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('position_settings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('filename', models.CharField(max_length=255, verbose_name='文件名')),
                ('file_hash', models.CharField(max_length=64, unique=True, verbose_name='文件哈希')),
                ('file_size', models.IntegerField(default=0, verbose_name='文件大小')),
                ('file_type', models.CharField(blank=True, max_length=50, verbose_name='文件类型')),
                ('candidate_name', models.CharField(max_length=100, verbose_name='候选人姓名')),
                ('content', models.TextField(verbose_name='简历内容')),
                ('status', models.CharField(choices=[('pending', '待筛选'), ('screened', '已筛选'), ('interviewing', '面试中'), ('analyzed', '已分析')], default='pending', max_length=20, verbose_name='状态')),
                ('screening_result', models.JSONField(blank=True, null=True, verbose_name='筛选结果')),
                ('screening_report', models.TextField(blank=True, null=True, verbose_name='筛选报告MD')),
                ('notes', models.TextField(blank=True, verbose_name='备注')),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resumes', to='position_settings.position', verbose_name='应聘岗位')),
            ],
            options={
                'verbose_name': '简历',
                'verbose_name_plural': '简历',
                'db_table': 'resumes',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['file_hash'], name='resumes_file_ha_d47e0e_idx'), models.Index(fields=['candidate_name'], name='resumes_candida_8b6f96_idx'), models.Index(fields=['status'], name='resumes_status_47e998_idx'), models.Index(fields=['position'], name='resumes_positio_9dcc70_idx')],
            },
        ),
    ]
