# Generated by Django 6.0 on 2025-12-06 14:16

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_screening', '0002_resumelibrary'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAssistSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('job_config', models.JSONField(default=dict, verbose_name='岗位配置')),
                ('qa_records', models.JSONField(default=list, verbose_name='问答记录')),
                ('final_report', models.JSONField(blank=True, null=True, verbose_name='最终报告')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='interview_assist_reports/%Y/%m/%d/', verbose_name='报告文件')),
                ('resume_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='resume_screening.resumedata', verbose_name='关联简历')),
            ],
            options={
                'verbose_name': '面试辅助会话',
                'verbose_name_plural': '面试辅助会话',
                'db_table': 'interview_assist_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
