# Generated by Django 6.0 on 2025-12-05 00:25

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume_screening', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewAssistSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('interviewer_name', models.CharField(max_length=100, verbose_name='面试官姓名')),
                ('job_config', models.JSONField(default=dict, verbose_name='岗位配置')),
                ('company_config', models.JSONField(default=dict, verbose_name='公司配置')),
                ('status', models.CharField(choices=[('active', '进行中'), ('paused', '暂停'), ('completed', '已完成')], default='active', max_length=20, verbose_name='状态')),
                ('current_round', models.IntegerField(default=0, verbose_name='当前轮次')),
                ('question_pool', models.JSONField(default=list, verbose_name='问题池')),
                ('resume_highlights', models.JSONField(default=list, verbose_name='简历亮点')),
                ('final_report', models.JSONField(blank=True, null=True, verbose_name='最终报告')),
                ('report_file', models.FileField(blank=True, null=True, upload_to='interview_assist_reports/%Y/%m/%d/', verbose_name='报告文件')),
                ('resume_data', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='resume_screening.resumedata', verbose_name='关联简历')),
            ],
            options={
                'verbose_name': '面试辅助会话',
                'verbose_name_plural': '面试辅助会话',
                'db_table': 'interview_assist_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InterviewQARecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('round_number', models.IntegerField(verbose_name='轮次')),
                ('question', models.TextField(verbose_name='提问内容')),
                ('question_source', models.CharField(choices=[('ai_suggested', 'AI建议'), ('ai_followup', 'AI追问建议'), ('ai_resume_based', 'AI基于简历'), ('hr_custom', 'HR自定义')], default='ai_suggested', max_length=20, verbose_name='问题来源')),
                ('question_category', models.CharField(blank=True, max_length=50, verbose_name='问题类别')),
                ('expected_skills', models.JSONField(default=list, verbose_name='考察技能')),
                ('question_difficulty', models.IntegerField(default=5, verbose_name='问题难度(1-10)')),
                ('related_interest_point', models.JSONField(blank=True, null=True, verbose_name='关联兴趣点')),
                ('answer', models.TextField(blank=True, verbose_name='候选人回答')),
                ('answer_recorded_at', models.DateTimeField(blank=True, null=True, verbose_name='回答记录时间')),
                ('answer_duration_seconds', models.IntegerField(blank=True, null=True, verbose_name='回答时长(秒)')),
                ('evaluation', models.JSONField(blank=True, null=True, verbose_name='评估结果')),
                ('followup_suggestions', models.JSONField(default=list, verbose_name='追问建议')),
                ('was_followed_up', models.BooleanField(default=False, verbose_name='是否已追问')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qa_records', to='interview_assist.interviewassistsession', verbose_name='所属会话')),
            ],
            options={
                'verbose_name': '面试问答记录',
                'verbose_name_plural': '面试问答记录',
                'db_table': 'interview_qa_records',
                'ordering': ['session', 'round_number'],
            },
        ),
    ]
