# Generated by Django 6.0 on 2025-12-13 14:43

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('qa_records', models.JSONField(default=list, verbose_name='问答记录')),
                ('final_report', models.JSONField(blank=True, null=True, verbose_name='面试报告')),
                ('resume', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interview_sessions', to='resume.resume', verbose_name='简历')),
            ],
            options={
                'verbose_name': '面试会话',
                'verbose_name_plural': '面试会话',
                'db_table': 'interview_sessions',
                'ordering': ['-created_at'],
            },
        ),
    ]
